LTO_ENABLE = yes

ENCODER_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_LOCK_ENABLE = yes
CAPS_WORD_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
CONSOLE_ENABLE = yes
KEYCODE_STRING_ENABLE = yes
VERBOSE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball

ALLOW_WARNINGS = yes
