// configuration
//#define EE_HANDS

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET

#define SPLIT_OLED_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#undef ENCODER_RESOLUTION
#define ENCODER_RESOLUTION 4

#define TAPPING_TERM 300

#define CAPS_WORD_INVERT_ON_SHIFT

#define OLED_FONT_H "font.c"

#define MOUSEKEY_OVERLAP_RESET

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 125
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 18
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_FRICTION 24
#define MOUSEKEY_MOVE_DELTA 1
