#CONVERT_TO = kb204
BOOTLOADER = rp2040
LTO_ENABLE = yes
ENCODER_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
#POINTING_DEVICE_ENABLE = yes
#POINTING_DEVICE_DRIVER = adns5050
KEY_LOCK_ENABLE = yes
CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = yes
VERBOSE = yes

# do not want
GRAVE_ESC_ENABLE = no
RGB_MATRIX_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENAGLE = no
BOOTMAGIC_ENABLE = no
SWAP_HANDS_ENABLE = no
COMMAND_ENABLE = no

ALLOW_WARNINGS = yes
