BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor
LTO_ENABLE = yes
ENCODER_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_LOCK_ENABLE = yes
CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = yes
VERBOSE = yes

ALLOW_WARNINGS = yes
