# non-negotiables
LTO_ENABLE = yes
RGB_MATRIX_ENABLE = yes
ENCODER_ENABLE = yes
OLED_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball

KEY_LOCK_ENABLE = yes
CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = no
VERBOSE = no

# do not want
GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENAGLE = no
BOOTMAGIC_ENABLE = no
SWAP_HANDS_ENABLE = no
COMMAND_ENABLE = no

ALLOW_WARNINGS = yes
